### ISSUE TITLE
Determine test coverage and identify blindspots

### ISSUE THREAD

**Issue by davehunt** [hackebrot/earth#1]
Earth 🌍 is such an important project, but I'm concerned that without adequate test coverage we may be leaving its users vulnerable. Let's identify the features that are not yet tested and ensure we can maintain excellent coverage in the future.

**Comment by hackebrot** [comment]
# Test Report

*Report generated on 12-Mar-2019 at 16:53:01 by [pytest-md]* 📝

[pytest-md]: https://github.com/hackebrot/pytest-md

## Summary

59 tests ran in 0.44 seconds ⏱

- 51 passed 😃
- 1 skipped 🙄
- 6 xfail 😞
- 1 error 😡
